security:
    acl:
        connection: default
    encoders:
        Anuncios\FrontendBundle\Entity\Usuario:        { algorithm: sha512, iterations: 10 }

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]        

    providers:
        usuarios:
            entity: { class: Anuncios\FrontendBundle\Entity\Usuario, property: username }

    firewalls:
        frontend:
            pattern:        ^/*
            provider:       usuarios
            anonymous:      ~
            form_login:
                login_path: autenticarse
                check_path: login_check
                require_previous_session: false
            logout:
                path:       logout
                    
    access_control:               
        - { path: ^/anuncios/nuevo/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/anuncios/*, roles: ROLE_USER }
        - { path: ^/admin/*, roles: ROLE_ADMIN }