<?php

namespace Anuncios\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository
{
    public function getCategorias()
    {
        $em = $this->getEntityManager();        
        $consulta = $em->createQuery('
            SELECT c
            FROM FrontendBundle:Categoria c
            ORDER BY c.prioridad ASC
        ');                        
        return $consulta->getArrayResult();
    }
    
    public function getCategoriasConAnuncios()
    {
        $em = $this->getEntityManager();        
        $consulta = $em->createQuery('
            SELECT c
            FROM FrontendBundle:Categoria c
        ');                        
        return $consulta->getArrayResult();
    }
    
    public function getTopCategorias($cant=3)
    {
        $em = $this->getEntityManager();        
        $consulta = $em->createQuery('
            SELECT c.slug, COUNT(a.categoria) AS Cantidad 
            FROM FrontendBundle:Anuncio a JOIN a.categoria c
            GROUP BY a.categoria
            ORDER BY Cantidad DESC
        ');
        $consulta->setMaxResults($cant);
        return $consulta->getArrayResult();
    }
}
