<?php

namespace Anuncios\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
    public function getUsuarios()
    {
        $em = $this->getEntityManager();        
        $consulta = $em->createQuery('
            SELECT u
            FROM FrontendBundle:Usuario u
        ');                        
        return $consulta->getArrayResult();
    }
}
